### ISSUE TITLE
is an m1 build supposed to work on an m2?

### ISSUE THREAD

**Issue by spinkney** [zarathucorp/shiny-electron-template-m1-2023#10]
I successfully built an app on my m1 and I shared it with a colleague who has an m2. They can unzip the file but when they try to open it it says "The application "my app name" can't be opened"

**Comment by jhk0530** [comment]
Use in M2 has not been confirmed, but I don't think it would make much difference.

which [maker](https://www.electronforge.io/config/makers) did you use?

**Comment by spinkney** [comment]
I did get it working and it's unrelated to being on M2. It may just be my company's IT policy or downloading the file from the company SharePoint.

When the zip file is downloaded from SharePoint, opened, and the user clicks on the application it returns an error. However, if it is opened within the SharePoint folder (through adding a shortcut from OneDrive) using Finder and the application is opened then it runs 🤔

**Comment by jhk0530** [comment]
I suspect it's a permissions (read/write) issue with your application, but I'm glad to hear it worked out for you.
