### ISSUE TITLE
"electron-forge start " successfully. but error with "electron-forge make", I used to "electron-forge make" successfully, but from now on it failed all the time.

### ISSUE THREAD

**Issue by wenjun-he** [zarathucorp/shiny-electron-template-m1-2023#7]
✔ Running preMake hook
✖ Making distributables
  › maker.clone is not a function
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
TypeError: maker.clone is not a function
at /usr/local/lib/node_modules/@electron-forge/cli/node_modules/@electron-forge/core/dist/api/make.js:120:45
    at /usr/local/lib/node_modules/@electron-forge/cli/node_modules/@electron-forge/core/dist/api/make.js:181:43
    at async Task.task (/usr/local/lib/node_modules/@electron-forge/cli/node_modules/@electron-forge/tracer/dist/index.js:58:20)
    at async Task.run (/usr/local/lib/node_modules/@electron-forge/cli/node_modules/listr2/dist/index.cjs:978:11)
    at async /usr/local/lib/node_modules/@electron-forge/cli/node_modules/p-map/index.js:57:22

**Comment by jhk0530** [comment]
Hi, is this different issue from previous one?

And

`TypeError: maker.clone is not a function`

is the first type of error I've seen.

Can you show your `packages.json` file?

**Comment by wenjun-he** [comment]
Thank you! the packages.json is the following:

{
  "name": "helloworld",
  "productName": "helloworld",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\""
  },
  "keywords": [],
  "author": "rachel",
    "dependencies": {
    "axios": "0.27.2",
    "electron-squirrel-startup": "^1.0.0",
    "esm": "^3.2.25",
    "execa": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.11",
    "@babel/plugin-transform-async-to-generator": "^7.22.5",
    "@babel/preset-env": "^7.22.10",
    "@babel/preset-react": "^7.22.5",
    "@electron-forge/cli": "^6.4.1",
    "@electron-forge/maker-dmg": "^6.4.1",
    "@electron-forge/maker-zip": "^6.4.1",
    "@electron-forge/plugin-auto-unpack-natives": "^6.4.1",
    "electron": "^26.1.0",
    "fs-extra": "^11.1.0"
  }
}

**Comment by wenjun-he** [comment]
I think it is the package version issue. I tried a lot and finally fixed it now.
