### ISSUE TITLE
How to transfer this project to the Window enviroment?

### ISSUE THREAD

**Issue by wenjun-he** [zarathucorp/shiny-electron-template-m1-2023#9]
How to transfer this project to the Window enviroment?  Is it possible?

**Comment by YonghuiDong** [comment]
> How to transfer this project to the Window enviroment?  Is it possible?

**Comment by YonghuiDong** [comment]
> How to transfer this project to the Window enviroment?  Is it possible?

Hi, you can try with my approach for windows OS. It is the easiest way to convert shiny app into a standalone desktop app.

Check it here: https://github.com/YonghuiDong/DesktopShiny

Best regards,

Yonghui

**Comment by jhk0530** [comment]
You may try [this repository](https://github.com/zarathucorp/shiny-electron-template-windows-2023)

However, there isn't guide or document in repository yet (at least for global users). 

We have [a guide](https://blog.zarathu.com/posts/2023-09-18-shinyexe/) in Korean on our blog, but translating it is not in our plans for the time being.

We hope you can follow along by looking at the images and code, but let us know if you find it difficult.

**Comment by wenjun-he** [comment]
> > How to transfer this project to the Window enviroment?  Is it possible?
> 
> Hi, you can try with my approach for windows OS. It is the easiest way to convert shiny app into a standalone desktop app.
> 
> Check it here: https://github.com/YonghuiDong/DesktopShiny
> 
> Best regards,
> 
> Yonghui

Thank for your tips. In your repo, it introduced that I should make my R shiny app as a R package firstly?

**Comment by wenjun-he** [comment]
> You may try [this repository](https://github.com/zarathucorp/shiny-electron-template-windows-2023)
> 
> However, there isn't guide or document in repository yet (at least for global users).
> 
> We have [a guide](https://blog.zarathu.com/posts/2023-09-18-shinyexe/) in Korean on our blog, but translating it is not in our plans for the time being.
> 
> We hope you can follow along by looking at the images and code, but let us know if you find it difficult.

I actually tried it the whole day. And electron-forge start successfully, can interact in the shiny app; while electron-forge make successfully, and I get the zip file, but the app in the zip file is always loading and can not be opened. The loading page is the following.
![WechatIMG276](https://github.com/zarathucorp/shiny-electron-template-m1-2023/assets/69523799/fcef4aaa-fe0d-4e56-9311-d4a0d8669886)

**Comment by jhk0530** [comment]
@wenjun-he 

In our case, some windows pc didn't work and this solution worked. 
but still some pc didn't work. 

1. Open shiny exe file with admin mode
2. Reboot PC and re-open it.

**Comment by wenjun-he** [comment]
Oh, I am sorry to hear that. I rebooted my PC, it did not work.

**Comment by jhk0530** [comment]
@wenjun-he 
I updated [window's template](https://github.com/zarathucorp/shiny-electron-template-windows), and checked it runs well with recent my personal work, you should check it.

Since there are some changes. I recommend to re-start (from fork) again with that template. 

If you have still problem. re-open this issue or create new one. 

Thanks !
